Quarkus Dapr Extension provides a DevService to enhance your experience with Quarkus and Dapr.

== Enabling / Disabling Dev Services for Dapr

Dev Services for Dapr are disabled by default unless:

- `quarkus.dapr.devservices.enabled` is set to `true`

== Setting Dapr image

Dev Services for Dapr uses the latest `daprio/daprd` image (`diagrid/daprd:latest`). You can change this image using the `quarkus.dapr.devservices.image-name` property.

== Adding Dapr Components

By default, Dapr DevServices create a Dapr container containing in-memory Pub/Sub and in-memory State Store building blocks.

If you want to add a custom Dapr component, you need to add it to the `src/main/resources/components` folder.

Example of Pub/Sub using Redis.

[source,yaml]
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
    - name: redisHost
      value: localhost:6379
    - name: redisPassword
      value: ""

Example of State Store using Redis:

[source,yaml]
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  version: v1
  metadata:
    - name: keyPrefix
      value: name
    - name: redisHost
      value: localhost:6379
    - name: redisPassword
      value: ""

== Network

By default, Dev Services for Dapr utilize a network named `dapr`.
Dev Services search for a Docker Network named `dapr`; if one does not exist, Dev Services create it.
